# theme: jekyll-theme-minima

title: CAAP Statistics 2022
logo: /assets/mixture-logo.png
description: This page is designed to maintain course materials for 2022 [CAAP](https://college.uchicago.edu/student-services/chicago-academic-achievement-program) Statistics Summer Session. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
